services:
  latestnews:
    image: ghcr.io/bruceblink/latestnews:latest
    container_name: latestnews
    ports:
      - '4444:4444'
    volumes:
      - newsnow_data:/usr/app/.data
    environment:
      # ⚠️ 只放「运行时」变量（Node / Nitro 用）
      NODE_ENV: production
      PORT: 4444
      INIT_TABLE: true
      ENABLE_CACHE: true
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped

volumes:
  newsnow_data:
    name: newsnow_data
